#!/usr/bin/env python3
"""Build an EDK2 TLS CA signature database and a C include from pinned PEM roots."""

from __future__ import annotations

import base64
import hashlib
import re
import struct
import sys
import uuid
from pathlib import Path

EFI_CERT_X509_GUID = uuid.UUID("a5c059a1-94e4-4aa7-87b5-ab155c2bf072")
SIGNATURE_OWNER_GUID = uuid.UUID("e056959d-53d4-4c21-9ff4-61726d363475")
EXPECTED_SHA256 = {
    "usertrust-rsa-certification-authority.pem":
        "e793c9b02fd8aa13e21c31228accb08119643b749c898964b1746d46c3d4cbd2",
    "usertrust-ecc-certification-authority.pem":
        "4ff460d54b9c86dabfbcfc5712e0400d2bed3fbc4d4fbdaa86e06adcd2a9ad7a",
    "isrg-root-x1.pem":
        "96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6",
}


def read_der(path: Path) -> bytes:
    text = path.read_text(encoding="ascii")
    match = re.fullmatch(
        r"\s*-----BEGIN CERTIFICATE-----\s*(.*?)\s*-----END CERTIFICATE-----\s*",
        text,
        flags=re.DOTALL,
    )
    if not match:
        raise ValueError(f"invalid PEM certificate: {path}")
    der = base64.b64decode("".join(match.group(1).split()), validate=True)
    actual = hashlib.sha256(der).hexdigest()
    expected = EXPECTED_SHA256.get(path.name)
    if expected is None or actual != expected:
        raise ValueError(f"unexpected certificate fingerprint for {path}: {actual}")
    return der


def signature_list(cert: bytes) -> bytes:
    signature_size = 16 + len(cert)
    list_size = 16 + 12 + signature_size
    return b"".join(
        (
            EFI_CERT_X509_GUID.bytes_le,
            struct.pack("<III", list_size, 0, signature_size),
            SIGNATURE_OWNER_GUID.bytes_le,
            cert,
        )
    )


def write_c_include(path: Path, data: bytes) -> None:
    lines = ["// Generated by tools/make_uefi_ca_bundle.py.",
             "STATIC CONST UINT8 mTinyGPTCaCerts[] = {"]
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines.extend(("};", ""))
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    if len(sys.argv) < 4:
        print(f"usage: {sys.argv[0]} OUTPUT.esl OUTPUT.inc CERT.pem...", file=sys.stderr)
        raise SystemExit(2)
    esl_path = Path(sys.argv[1])
    include_path = Path(sys.argv[2])
    cert_paths = [Path(value) for value in sys.argv[3:]]
    data = b"".join(signature_list(read_der(path)) for path in cert_paths)
    esl_path.parent.mkdir(parents=True, exist_ok=True)
    include_path.parent.mkdir(parents=True, exist_ok=True)
    esl_path.write_bytes(data)
    write_c_include(include_path, data)
    print(f"Created {esl_path} and {include_path} ({len(data)} bytes, {len(cert_paths)} roots)")


if __name__ == "__main__":
    main()
